import '../action_config.dart';

// ═══════════════════════════════════════════════════════════════
// Per-Action Presets — base config for each action type
// ═══════════════════════════════════════════════════════════════

ActionConfig _leftClickPreset() => ActionConfig(
      textKind: '数字飘字',
      textEnabled: true,
      textContent: '+1',
      textTags: ['功德 +1', '继续点击', '已触发'],
      textColor: '#B45309',
      textDuration: 1000,
      textEasing: '弹跳',
      textWeight: '加粗',
      textShadow: '柔和',
      comboEnabled: true,
      textOffsetY: -28,
      particle: true,
      particleCount: 22,
      particleSpread: 62,
      particleStyle: '火花',
      particleDirection: '四周扩散',
      particleDuration: 780,
      particleSize: 14,
      particleOpacity: 88,
      particleGravity: 8,
      particleBounce: 14,
      ripple: true,
      rippleSize: 72,
      rippleDuration: 860,
      rippleStyle: '回声环',
      rippleEasing: '缓出',
      rippleOpacity: 72,
      sound: true,
      fontSize: 24,
      volume: 72,
      soundFadeOut: 80,
      soundTriggerMode: '每次触发',
      shake: 48,
      cursorOverride: '木鱼（继承默认）',
      cursorSize: 48,
      cursorTrailEnabled: true,
      cursorTrailCount: 4,
      cursorTrailOpacity: 36,
      cursorGlowColor: '#F59E0B',
      imageEnabled: false,
      triggerTiming: '抬起时',
      triggerZone: '当前页面可点击区域',
      holdMs: 0,
      soundFile: 'woodfish-soft.wav',
    );

ActionConfig _rightClickPreset() => ActionConfig(
      textKind: '文本飘字',
      textEnabled: false,
      textContent: 'menu',
      textTags: ['展开菜单', '右键操作', '更多选项'],
      textColor: '#475569',
      textDuration: 820,
      textEasing: '缓出',
      textWeight: '中等',
      textShadow: '无',
      textOffsetY: -18,
      particle: true,
      particleCount: 14,
      particleSpread: 40,
      particleDirection: '四周扩散',
      particleDuration: 560,
      particleSize: 10,
      particleOpacity: 72,
      ripple: true,
      rippleSize: 50,
      rippleDuration: 560,
      rippleStyle: '双环',
      rippleEasing: '缓出',
      rippleOpacity: 62,
      sound: false,
      fontSize: 18,
      volume: 60,
      soundFadeOut: 40,
      soundTriggerMode: '节流播放',
      shake: 22,
      cursorOverride: '跟随当前状态',
      cursorSize: 44,
      imageEnabled: false,
      triggerTiming: '菜单弹出前',
      triggerZone: '右键菜单前',
      holdMs: 0,
      soundFile: 'tick-light.wav',
    );

ActionConfig _doubleClickPreset() => ActionConfig(
      textKind: '数字飘字',
      textStyle: '英文单词 (one, two, three)',
      textMode: '模板模式',
      textTemplate: 'combo \${number}',
      textEnabled: true,
      textContent: 'combo',
      textTags: ['双击完成', '连击命中', 'combo'],
      textTagPlayMode: '随机显示',
      textColor: '#0F766E',
      textDuration: 1100,
      textEasing: '弹性',
      textWeight: '加粗',
      textOutlineWidth: 1,
      textShadow: '柔和',
      comboEnabled: true,
      textOffsetY: -30,
      particle: true,
      particleCount: 26,
      particleSpread: 74,
      particleStyle: '火花',
      particleDirection: '四周扩散',
      particleColorMode: '随机轻变化',
      particlePalette: ['#14B8A6', '#0F766E', '#5EEAD4', '#99F6E4', '#CCFBF1'],
      particleDuration: 980,
      particleSize: 16,
      particleOpacity: 96,
      ripple: true,
      rippleSize: 84,
      rippleDuration: 940,
      rippleStyle: '双环',
      rippleEasing: '弹性',
      rippleLineWidth: 3,
      rippleOpacity: 84,
      rippleColor: '#14B8A6',
      sound: true,
      fontSize: 24,
      volume: 80,
      playbackRate: 104,
      soundFadeOut: 90,
      soundTriggerMode: '连击叠加',
      soundBlendMode: '压低页面音频',
      shake: 52,
      cursorOverride: '木鱼（增强态）',
      cursorSize: 52,
      cursorTrailEnabled: true,
      cursorTrailCount: 5,
      cursorTrailOpacity: 42,
      cursorGlowColor: '#14B8A6',
      imageEnabled: false,
      triggerTiming: '第二次抬起后',
      triggerZone: '双击命中区域',
      holdMs: 320,
      soundFile: 'woodfish-deep.wav',
    );

ActionConfig _longPressPreset() => ActionConfig(
      textKind: '文本飘字',
      textStyle: '中文数字 (一, 二, 三)',
      textEnabled: false,
      textContent: '蓄',
      textTags: ['按住中', '蓄力完成', '松开触发'],
      textColor: '#7C3AED',
      textDuration: 900,
      textEasing: '缓入缓出',
      textOpacity: 94,
      textWeight: '中等',
      textShadow: '柔和',
      textOffsetY: -22,
      particle: true,
      particleCount: 16,
      particleSpread: 48,
      particleStyle: '碎屑粒子',
      particleDirection: '向上喷发',
      particlePalette: ['#A78BFA', '#7C3AED', '#C4B5FD', '#DDD6FE', '#EDE9FE'],
      particleDuration: 740,
      particleSize: 12,
      particleOpacity: 78,
      ripple: true,
      rippleSize: 62,
      rippleDuration: 780,
      rippleStyle: '柔和面波',
      rippleEasing: '缓入缓出',
      rippleOpacity: 56,
      rippleColor: '#A78BFA',
      sound: true,
      fontSize: 20,
      volume: 72,
      playbackRate: 92,
      soundDelay: 60,
      soundFadeOut: 120,
      soundTriggerMode: '每次触发',
      soundBlendMode: '压低页面音频',
      shake: 58,
      cursorOverride: '木鱼（按压态）',
      cursorSize: 50,
      imageEnabled: false,
      triggerTiming: '松开后触发',
      triggerZone: '按住后释放',
      holdMs: 560,
      soundFile: 'woodfish-deep.wav',
    );

ActionConfig _wheelPreset() => ActionConfig(
      textKind: '文本飘字',
      textEnabled: false,
      textContent: 'roll',
      textTags: ['向上滚动', '向下滚动', '继续滚动'],
      textTagPlayMode: '随机显示',
      textColor: '#0284C7',
      textDuration: 700,
      textEasing: '线性',
      textOpacity: 90,
      textWeight: '常规',
      textShadow: '无',
      textOffsetY: -14,
      particle: true,
      particleCount: 10,
      particleSpread: 36,
      particleDirection: '四周扩散',
      particleColorMode: '跟随飘字色',
      particleDuration: 460,
      particleSize: 10,
      particleOpacity: 72,
      ripple: true,
      rippleSize: 38,
      rippleDuration: 500,
      rippleStyle: '单环',
      rippleEasing: '线性',
      rippleLineWidth: 1,
      rippleOpacity: 46,
      rippleColor: '#0284C7',
      sound: false,
      fontSize: 16,
      volume: 40,
      playbackRate: 110,
      soundFadeOut: 30,
      soundTriggerMode: '节流播放',
      shake: 16,
      cursorOverride: '跟随当前状态',
      cursorSize: 44,
      imageEnabled: false,
      triggerTiming: '连续滚动中',
      triggerZone: '向上 / 向下滚轮',
      holdMs: 180,
      soundFile: 'tick-light.wav',
    );

ActionConfig _hoverPreset() => ActionConfig(
      textKind: '文本飘字',
      textEnabled: false,
      textContent: 'hover',
      textTags: ['已聚焦', '经过目标', '可点击'],
      textTagPlayMode: '随机显示',
      textColor: '#475569',
      textDuration: 680,
      textEasing: '缓入缓出',
      textOpacity: 88,
      textWeight: '常规',
      textShadow: '无',
      textOffsetY: -12,
      particle: false,
      particleCount: 8,
      particleSpread: 24,
      particleDirection: '向上喷发',
      particleDuration: 420,
      particleSize: 8,
      particleOpacity: 60,
      ripple: true,
      rippleSize: 34,
      rippleDuration: 440,
      rippleStyle: '柔和面波',
      rippleEasing: '缓入缓出',
      rippleLineWidth: 1,
      rippleOpacity: 32,
      rippleColor: '#94A3B8',
      sound: false,
      fontSize: 16,
      volume: 0,
      soundFadeOut: 0,
      soundTriggerMode: '节流播放',
      shake: 0,
      cursorOverride: '切换到 pointer',
      cursorSize: 44,
      imageEnabled: false,
      triggerTiming: '停留后',
      triggerZone: '进入可交互元素',
      holdMs: 220,
      soundFile: 'tick-light.wav',
    );

ActionConfig presetForAction(String actionId) {
  switch (actionId) {
    case 'leftClick':
      return _leftClickPreset();
    case 'rightClick':
      return _rightClickPreset();
    case 'doubleClick':
      return _doubleClickPreset();
    case 'longPress':
      return _longPressPreset();
    case 'wheel':
      return _wheelPreset();
    case 'hover':
      return _hoverPreset();
    default:
      return ActionConfig();
  }
}
