// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'action_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ActionConfigImpl _$$ActionConfigImplFromJson(Map<String, dynamic> json) =>
    _$ActionConfigImpl(
      triggerTiming: json['triggerTiming'] as String? ?? '抬起时',
      triggerZone: json['triggerZone'] as String? ?? '当前页面可点击区域',
      holdMs: (json['holdMs'] as num?)?.toInt() ?? 0,
      textEnabled: json['textEnabled'] as bool? ?? false,
      textKind: json['textKind'] as String? ?? '数字飘字',
      textStyle: json['textStyle'] as String? ?? '阿拉伯数字 (1, 2, 3)',
      textMode: json['textMode'] as String? ?? '默认模式 (+1)',
      textTemplate: json['textTemplate'] as String? ?? r'${number}',
      textContent: json['textContent'] as String? ?? '',
      textTags:
          (json['textTags'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          const [],
      textTagPlayMode: json['textTagPlayMode'] as String? ?? '按顺序显示',
      textColor: json['textColor'] as String? ?? '#B45309',
      textDuration: (json['textDuration'] as num?)?.toInt() ?? 1000,
      textEasing: json['textEasing'] as String? ?? '弹跳',
      textOpacity: (json['textOpacity'] as num?)?.toInt() ?? 100,
      textFontFamily: json['textFontFamily'] as String? ?? '系统默认',
      textWeight: json['textWeight'] as String? ?? '加粗',
      textOutlineWidth: (json['textOutlineWidth'] as num?)?.toInt() ?? 0,
      textShadow: json['textShadow'] as String? ?? '柔和',
      comboEnabled: json['comboEnabled'] as bool? ?? false,
      comboWindowMs: (json['comboWindowMs'] as num?)?.toInt() ?? 900,
      textOffsetX: (json['textOffsetX'] as num?)?.toInt() ?? 0,
      textOffsetY: (json['textOffsetY'] as num?)?.toInt() ?? -28,
      fontSize: (json['fontSize'] as num?)?.toInt() ?? 24,
      textGradient: json['textGradient'] as bool? ?? false,
      textGradientStart: json['textGradientStart'] as String? ?? '#FBBF24',
      textGradientEnd: json['textGradientEnd'] as String? ?? '#EC4899',
      textDelay: (json['textDelay'] as num?)?.toInt() ?? 0,
      particle: json['particle'] as bool? ?? false,
      particleCount: (json['particleCount'] as num?)?.toInt() ?? 22,
      particleSpread: (json['particleSpread'] as num?)?.toInt() ?? 62,
      particleStyle: json['particleStyle'] as String? ?? '点状粒子',
      particleDirection: json['particleDirection'] as String? ?? '四周扩散',
      particleColorMode: json['particleColorMode'] as String? ?? '跟随主题',
      particleDuration: (json['particleDuration'] as num?)?.toInt() ?? 780,
      particleSize: (json['particleSize'] as num?)?.toInt() ?? 14,
      particleOpacity: (json['particleOpacity'] as num?)?.toInt() ?? 88,
      particlePalette:
          (json['particlePalette'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          const ['#FBBF24', '#F59E0B', '#FDE68A', '#FCD34D', '#FEF3C7'],
      particleGravity: (json['particleGravity'] as num?)?.toInt() ?? 0,
      particleWind: (json['particleWind'] as num?)?.toInt() ?? 0,
      particleBounce: (json['particleBounce'] as num?)?.toInt() ?? 0,
      particleTrail: json['particleTrail'] as bool? ?? false,
      particleDelay: (json['particleDelay'] as num?)?.toInt() ?? 0,
      particleMotionMode: json['particleMotionMode'] as String? ?? 'burst',
      orbitalCount: (json['orbitalCount'] as num?)?.toInt() ?? 6,
      orbitalRadius: (json['orbitalRadius'] as num?)?.toInt() ?? 32,
      orbitalSpeed: (json['orbitalSpeed'] as num?)?.toInt() ?? 3,
      ripple: json['ripple'] as bool? ?? false,
      rippleSize: (json['rippleSize'] as num?)?.toInt() ?? 72,
      rippleDuration: (json['rippleDuration'] as num?)?.toInt() ?? 860,
      rippleStyle: json['rippleStyle'] as String? ?? '单环',
      rippleEasing: json['rippleEasing'] as String? ?? '缓出',
      rippleLineWidth: (json['rippleLineWidth'] as num?)?.toInt() ?? 2,
      rippleOpacity: (json['rippleOpacity'] as num?)?.toInt() ?? 72,
      rippleColor: json['rippleColor'] as String? ?? '#F59E0B',
      rippleDelay: (json['rippleDelay'] as num?)?.toInt() ?? 0,
      sound: json['sound'] as bool? ?? false,
      soundFile: json['soundFile'] as String? ?? 'click.wav',
      volume: (json['volume'] as num?)?.toInt() ?? 80,
      playbackRate: (json['playbackRate'] as num?)?.toInt() ?? 100,
      soundDelay: (json['soundDelay'] as num?)?.toInt() ?? 0,
      soundFadeOut: (json['soundFadeOut'] as num?)?.toInt() ?? 0,
      soundTriggerMode: json['soundTriggerMode'] as String? ?? '每次触发',
      soundBlendMode: json['soundBlendMode'] as String? ?? '叠加',
      animationEnabled: json['animationEnabled'] as bool? ?? false,
      animationStyle: json['animationStyle'] as String? ?? '缩放脉冲',
      animationDuration: (json['animationDuration'] as num?)?.toInt() ?? 600,
      animationEasing: json['animationEasing'] as String? ?? '弹性',
      animationScale: (json['animationScale'] as num?)?.toInt() ?? 120,
      animationOpacity: (json['animationOpacity'] as num?)?.toInt() ?? 100,
      animationOffsetX: (json['animationOffsetX'] as num?)?.toInt() ?? 0,
      animationOffsetY: (json['animationOffsetY'] as num?)?.toInt() ?? 0,
      animationColor: json['animationColor'] as String? ?? '#F59E0B',
      animationGlow: json['animationGlow'] as bool? ?? false,
      animationDelay: (json['animationDelay'] as num?)?.toInt() ?? 0,
      imageEnabled: json['imageEnabled'] as bool? ?? false,
      imageDataUrl: json['imageDataUrl'] as String? ?? '',
      imageDuration: (json['imageDuration'] as num?)?.toInt() ?? 1000,
      imageSize: (json['imageSize'] as num?)?.toInt() ?? 64,
      imageOpacity: (json['imageOpacity'] as num?)?.toInt() ?? 100,
      imageOffsetX: (json['imageOffsetX'] as num?)?.toInt() ?? 0,
      imageOffsetY: (json['imageOffsetY'] as num?)?.toInt() ?? 0,
      imageDelay: (json['imageDelay'] as num?)?.toInt() ?? 0,
    );

Map<String, dynamic> _$$ActionConfigImplToJson(_$ActionConfigImpl instance) =>
    <String, dynamic>{
      'triggerTiming': instance.triggerTiming,
      'triggerZone': instance.triggerZone,
      'holdMs': instance.holdMs,
      'textEnabled': instance.textEnabled,
      'textKind': instance.textKind,
      'textStyle': instance.textStyle,
      'textMode': instance.textMode,
      'textTemplate': instance.textTemplate,
      'textContent': instance.textContent,
      'textTags': instance.textTags,
      'textTagPlayMode': instance.textTagPlayMode,
      'textColor': instance.textColor,
      'textDuration': instance.textDuration,
      'textEasing': instance.textEasing,
      'textOpacity': instance.textOpacity,
      'textFontFamily': instance.textFontFamily,
      'textWeight': instance.textWeight,
      'textOutlineWidth': instance.textOutlineWidth,
      'textShadow': instance.textShadow,
      'comboEnabled': instance.comboEnabled,
      'comboWindowMs': instance.comboWindowMs,
      'textOffsetX': instance.textOffsetX,
      'textOffsetY': instance.textOffsetY,
      'fontSize': instance.fontSize,
      'textGradient': instance.textGradient,
      'textGradientStart': instance.textGradientStart,
      'textGradientEnd': instance.textGradientEnd,
      'textDelay': instance.textDelay,
      'particle': instance.particle,
      'particleCount': instance.particleCount,
      'particleSpread': instance.particleSpread,
      'particleStyle': instance.particleStyle,
      'particleDirection': instance.particleDirection,
      'particleColorMode': instance.particleColorMode,
      'particleDuration': instance.particleDuration,
      'particleSize': instance.particleSize,
      'particleOpacity': instance.particleOpacity,
      'particlePalette': instance.particlePalette,
      'particleGravity': instance.particleGravity,
      'particleWind': instance.particleWind,
      'particleBounce': instance.particleBounce,
      'particleTrail': instance.particleTrail,
      'particleDelay': instance.particleDelay,
      'particleMotionMode': instance.particleMotionMode,
      'orbitalCount': instance.orbitalCount,
      'orbitalRadius': instance.orbitalRadius,
      'orbitalSpeed': instance.orbitalSpeed,
      'ripple': instance.ripple,
      'rippleSize': instance.rippleSize,
      'rippleDuration': instance.rippleDuration,
      'rippleStyle': instance.rippleStyle,
      'rippleEasing': instance.rippleEasing,
      'rippleLineWidth': instance.rippleLineWidth,
      'rippleOpacity': instance.rippleOpacity,
      'rippleColor': instance.rippleColor,
      'rippleDelay': instance.rippleDelay,
      'sound': instance.sound,
      'soundFile': instance.soundFile,
      'volume': instance.volume,
      'playbackRate': instance.playbackRate,
      'soundDelay': instance.soundDelay,
      'soundFadeOut': instance.soundFadeOut,
      'soundTriggerMode': instance.soundTriggerMode,
      'soundBlendMode': instance.soundBlendMode,
      'animationEnabled': instance.animationEnabled,
      'animationStyle': instance.animationStyle,
      'animationDuration': instance.animationDuration,
      'animationEasing': instance.animationEasing,
      'animationScale': instance.animationScale,
      'animationOpacity': instance.animationOpacity,
      'animationOffsetX': instance.animationOffsetX,
      'animationOffsetY': instance.animationOffsetY,
      'animationColor': instance.animationColor,
      'animationGlow': instance.animationGlow,
      'animationDelay': instance.animationDelay,
      'imageEnabled': instance.imageEnabled,
      'imageDataUrl': instance.imageDataUrl,
      'imageDuration': instance.imageDuration,
      'imageSize': instance.imageSize,
      'imageOpacity': instance.imageOpacity,
      'imageOffsetX': instance.imageOffsetX,
      'imageOffsetY': instance.imageOffsetY,
      'imageDelay': instance.imageDelay,
    };
